plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
destination: docs
exclude:
  - README.adoc
  - Notes.txt
title: "Ma cantine"
tagline: "Un site concernant le choix bien réfléchi des menus d’une cantine hypothétique"
description: "Une étude scientifique concernant le jugement réfléchi"
lang: fr
